name: Rust

on:
  push:
    branches: [ main ]
    paths:
    - 'firestore-serde'
    - 'firestore-serde-timestamp'
    - 'Cargo.toml'
    - 'Cargo.lock'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Run v1beta1 tests
      run: cargo test -p firestore-serde --no-default-features --features=google-firestore-v1beta1
